# Generated by Django 5.2.6 on 2025-09-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_course_enrollment_worktime"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="usermame",
            field=models.CharField(default="us", max_length=100),
        ),
    ]
