# Generated by Django 5.2.6 on 2025-09-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_student_usermame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='usermame',
            field=models.CharField(default='us', max_length=100),
        ),
    ]
