# Generated by Django 5.2.6 on 2025-10-15 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0006_remove_student_usermame_alter_student_username"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="enrollment",
            table="enrollment",
        ),
    ]
