# Generated by Django 5.2.6 on 2025-10-15 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0007_alter_enrollment_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table="student",
        ),
    ]
